# Generated by Django 4.1.2 on 2023-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceworld', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=25)),
            ],
        ),
    ]
