# Generated by Django 4.1.2 on 2023-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceworld', '0002_providermember'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermember',
            name='lat',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providermember',
            name='lng',
            field=models.FloatField(default=90),
            preserve_default=False,
        ),
    ]
