# Generated by Django 4.1.2 on 2023-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceworld', '0003_providermember_lat_providermember_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
